# You can remove the 'version' line (Compose v2 doesn't need it)
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    command: ["redis-server", "--save", "60", "1"]

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file: .env
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: celery -A config.celery_app worker -l info
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  beat:
    build: .
    command: celery -A config.celery_app beat -l info
    env_file: .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
